= GNU Arm Embedded Image
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Buildah: https://buildah.io/[Buildah]
:Fedora: https://getfedora.org/[Fedora]
:GCC: https://gcc.gnu.org/[GCC]
:GNU-Arm-Embedded-Toolchain: https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads[GNU Arm Embedded Toolchain]
:OpenSSH: https://www.openssh.com/[OpenSSH]
:Podman: https://podman.io/[Podman]

image:https://img.shields.io/github/workflow/status/jwillikers/gnu-arm-embedded-image/CI/main[GitHub Workflow Status]

A container image for running the {GNU-Arm-Embedded-Toolchain} for C and {cpp}, built on {Fedora}.
Comes complete with CMake, Conan, Ninja, and Clang tools.

== Quick Start

Supported architectures:: `amd64`, `arm32v7`, `arm64v8`

Run the container with {Podman} to access the GNU Arm Embedded Toolchain.
The following example enters the container, mounting the current working directory, Conan's configuration directory, and Git's configuration directory.
In addition, it mounts the device `/dev/ttyBmpGdb`, a serial console, inside the container.

[source,sh]
----
podman run \
    --rm \
    --userns keep-id \
    --group-add keep-groups \
    --device /dev/ttyBmpGdb:/dev/ttyBmpGdb \
    --security-opt label=disable \
    --volume "$PWD":/home/user \
    --volume "$HOME/.conan":/home/user/.conan \
    --volume "$HOME/.config/git":/home/user/.git/config \
    --name gnu-arm-embedded \
    -it \
    localhost/gnu-arm-embedded:latest conan install ..
----

Or just open a shell inside the container.

[source,sh]
----
podman run --rm -it --volume "$HOME":/home/user:Z --name gnu-arm-embedded quay.io/jwillikers/gnu-arm-embedded:latest
----

== Build

Use {Buildah} to build the image.

. Install the necessary dependencies.
+
[source,sh]
----
sudo dnf -y install git buildah podman
----

. Clone this repository.
+
[source,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/gnu-arm-embedded-image.git
----

. Run the shell script.
+
[source,sh]
----
~/Projects/gcc-image/gnu-arm-embedded-image.sh
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[Asciidoctor]
* {Buildah}
* {Fedora}
* {GCC}
* https://git-scm.com/[Git]
* https://www.linuxfoundation.org/[Linux]
* {OpenSSH}
* {Podman}
* https://www.python.org/[Python]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[Code of Conduct] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
